### Load Numpy

In [2]:
! pip install numpy

In [3]:
import numpy as np


### The Basics

In [ ]:
# Create a numpy array
a=np.array([1,2,3,4],dtype='int32')
print(a)

[1 2 3 4]


In [5]:
# Get Dimension
a.ndim

1

In [6]:
# Get size(return size bytes of one element in an array)
a.itemsize

4

In [7]:
# Get Shape
a.shape

(4,)

In [8]:
# Get Type
a.dtype

dtype('int32')

In [9]:
# Get total items
a.nbytes

16

In [10]:
# Get no.of elements
a.size

4

### Accessing/Changing specific elements,rows,columns

In [11]:
a=np.array([[1,2,3,4,5,6,7,8],[9,10,11,12,13,14,15,16]])
print(a)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [ ]:
# Access specific element [r, c]
a[0,5]

6

In [ ]:
# Access specific row
a[1,:]

array([ 9, 10, 11, 12, 13, 14, 15, 16])

In [ ]:
# Access specific column
a[:,2]

array([ 3, 11])

In [ ]:
# Access elements with step
a[0,0:-1:2] # start:end:step

array([1, 3, 5, 7])

In [16]:
a[1,5] = 20

a[:,2] = [100,200]
print(a)

[[  1   2 100   4   5   6   7   8]
 [  9  10 200  12  13  20  15  16]]


##### 3d array

In [17]:
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [18]:
# Get specific element
a[0,1,1]

4

In [19]:
a[0,:,1]

array([2, 4])

In [ ]:
# Replace
a[:,1,:]=[[9,9],[8,8]]
a

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing different types of Arrays

In [21]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
# All 1s matrix
np.ones((2,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [25]:
# Identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Fill with a number
np.full((2,2),15)

array([[15, 15],
       [15, 15]])

In [ ]:
# Fill with a number in similar shaped array
np.full_like(a,15)

array([[[15, 15],
        [15, 15]],

       [[15, 15],
        [15, 15]]])

In [34]:
# Random decimal number
np.random.rand(2,3,2)

array([[[0.01848224, 0.74387532],
        [0.76315166, 0.14327953],
        [0.37402821, 0.60704549]],

       [[0.34680063, 0.22068387],
        [0.51473627, 0.88071175],
        [0.46512575, 0.70288375]]])

In [37]:
# Random integers
np.random.randint(1,15,size=(3,2))

array([[ 9,  7],
       [13, 13],
       [ 6, 12]])

In [42]:
# Repeat an array
a = np.array([[1,2,3]])
b = np.repeat(a,3,axis=0)
b

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [49]:
# Copy an array
a = np.array([1,2,3])
b = a.copy()
b[1] = 9
b


array([1, 9, 3])