### Load Numpy

In [22]:
! pip install numpy

In [23]:
import numpy as np


### The Basics

In [24]:
# Create a numpy array
a=np.array([1,2,3,4],dtype='int32')
print(a)

[1 2 3 4]


In [25]:
# Get Dimension
a.ndim

1

In [26]:
# Get size(return size bytes of one element in an array)
a.itemsize

4

In [27]:
# Get Shape
a.shape

(4,)

In [28]:
# Get Type
a.dtype

dtype('int32')

In [29]:
# Get total items
a.nbytes

16

In [30]:
# Get no.of elements
a.size

4

### Accessing/Changing specific elements,rows,columns

In [31]:
a=np.array([[1,2,3,4,5,6,7,8],[9,10,11,12,13,14,15,16]])
print(a)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [32]:
# Access specific element [r, c]
a[0,5]

6

In [33]:
# Access specific row
a[1,:]

array([ 9, 10, 11, 12, 13, 14, 15, 16])

In [34]:
# Access specific column
a[:,2]

array([ 3, 11])

In [35]:
# Access elements with step
a[0,0:-1:2] # start:end:step

array([1, 3, 5, 7])

In [36]:
a[1,5] = 20

a[:,2] = [100,200]
print(a)

[[  1   2 100   4   5   6   7   8]
 [  9  10 200  12  13  20  15  16]]


##### 3d array

In [37]:
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [38]:
# Get specific element
a[0,1,1]

4

In [39]:
a[0,:,1]

array([2, 4])

In [40]:
# Replace
a[:,1,:]=[[9,9],[8,8]]
a

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing different types of Arrays

In [41]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [42]:
# All 1s matrix
np.ones((2,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [43]:
# Identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
# Fill with a number
np.full((2,2),15)

array([[15, 15],
       [15, 15]])

In [45]:
# Fill with a number in similar shaped array
np.full_like(a,15)

array([[[15, 15],
        [15, 15]],

       [[15, 15],
        [15, 15]]])

In [46]:
# Random decimal number
np.random.rand(2,3,2)

array([[[0.78039099, 0.90288948],
        [0.17227618, 0.22390108],
        [0.43497665, 0.14955573]],

       [[0.60426048, 0.17122408],
        [0.69060207, 0.42631561],
        [0.76095987, 0.67949085]]])

In [47]:
# Random integers
np.random.randint(1,15,size=(3,2))

array([[13,  7],
       [ 6,  1],
       [ 5,  9]])

In [48]:
# Repeat an array
a = np.array([[1,2,3]])
b = np.repeat(a,3,axis=0)
b

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [49]:
# Copy an array
a = np.array([1,2,3])
b = a.copy()
b[1] = 9
b


array([1, 9, 3])

### Mathematics

In [50]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [51]:
a+2

array([3, 4, 5, 6])

In [52]:
a-2

array([-1,  0,  1,  2])

In [53]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [54]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [55]:
a**2

array([ 1,  4,  9, 16])

In [56]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### Linear Algebra

In [57]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

# Matrix multiplication
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [58]:
#  Determinant of matrix
c = np.identity(3)
np.linalg.det(c)

1.0

For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)
- Determinant
- Trace
- Singular Vector Decomposition
- Eigenvalues
- Matrix Norm
- Inverse
- Etc...

#### Statistics

In [59]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
np.min(stats)

1

In [61]:
np.max(stats)

6

In [62]:
np.sum(stats)

21

### Reorganizing Arrays

In [63]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
b = a.reshape((3,2))
b

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [64]:
# Vertical stacking vectors
a = np.array([1,2,3])
b = np.array([5,6,7])
np.vstack([a,b,a,b])

array([[1, 2, 3],
       [5, 6, 7],
       [1, 2, 3],
       [5, 6, 7]])

In [65]:
# Horizontal stacking vectors
np.hstack([a,b])

array([1, 2, 3, 5, 6, 7])